import type { Metadata } from 'next';

import '~/features/app/css/globals.css';
import { NextAuthProviders } from '~/lib/nextauth-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <NextAuthProviders>
        <body>{children}</body>
      </NextAuthProviders>
    </html>
  );
}
